#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : ##https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Timebox management

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Noel Conde Algarra                                
your_link                                 : ##https://noelcadev.github.io                     
your_city                                 : Spain                                
email_address                             : ## noel
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : devnoel_ca
github_username                           : noelcadev
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Timeboxing
    description                           : Plan your work using the timeboxing technique
    fontawesome_icon_name                 : clock
    
  - title                                 : Exercises
    description                           : Create your own exercise routines. You will receive notifications when you complete the exercises.
    fontawesome_icon_name                 : dumbbell

  - title                                 : Plans
    description                           : Create as many timebox plans as you want with the pro version.
    fontawesome_icon_name                 : bars

  - title                                 : Timers
    description                           : Customize your plan by adding as many timers as you want. You will be notified when you complete a block of time and when you finish the entire plan.
    fontawesome_icon_name                 : hourglass

  - title                                 : Reorder
    description                           : Adapt your plan to the needs of the day by rearranging timers.
    fontawesome_icon_name                 : list

  - title                                 : Chain timers
    description                           : Plans can be continuous, they continue to run automatically when they finish a block of time. You can also configure them so that you have to trigger each timer manually..
    fontawesome_icon_name                 : link
  
  - title                                 : Colors
    description                           : Customize timers with colors
    fontawesome_icon_name                 : paint-roller

  - title                                 : Adapt
    description                           : Do you need more time to finish a task? Add minutes on the fly with a button by adapting it to the needs of the moment.
    fontawesome_icon_name                 : plus

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : Timebox pro
    description                           : Access all features. Unlimited plans, unlimited timers, change app icon
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#225957"                                 # 1B3636
cover_overlay_transparency                : 0.93

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1E7477"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#1d63ea"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
